import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect, useRouter } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import { FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Colors, Spacing, Typography, useTheme } from "../../core/theme";
import { GradeBookRepository } from "../../features/grades/GradeBookRepository";
import { GroupScheduleRepository } from "../../features/groups/GroupScheduleRepository";
import { Group } from "../../shared/types";
import { AppInput, EmptyState } from "../../shared/components";
import { smartSearch } from "../../shared/utils/smartSearch";

const DAYS = ["الأحد", "الإثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"];

export default function GradeGroupsScreen() {
  const router = useRouter(); const { colors } = useTheme();
  const [groups, setGroups] = useState<Group[]>([]); const [query, setQuery] = useState("");
  const load = useCallback(() => { try { setGroups(GradeBookRepository.getGroups()); } catch { setGroups([]); } }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const visible = useMemo(() => smartSearch(groups, query, [{ get: (g) => g.name, weight: 1.2 }, { get: (g) => g.subjectName }, { get: (g) => g.teacherName }, { get: (g) => g.grade }]), [groups, query]);
  return <SafeAreaView style={[styles.safe, { backgroundColor: colors.background }]}><View style={styles.header}><TouchableOpacity onPress={() => router.back()} style={[styles.back, { backgroundColor: colors.cardBackground, borderColor: colors.border }]}><Ionicons name="chevron-forward" size={22} color={colors.textPrimary} /></TouchableOpacity><View style={styles.copy}><Text style={[styles.eyebrow, { color: colors.primary }]}>الأداء الأكاديمي</Text><Text style={[styles.title, { color: colors.textPrimary }]}>رصد الدرجات</Text><Text style={[styles.subtitle, { color: colors.textSecondary }]}>اختر مجموعة لفتح صفحة الرصد الحالية</Text></View><View style={[styles.count, { backgroundColor: colors.primaryLight }]}><Text style={[styles.countText, { color: colors.primary }]}>{groups.length}</Text></View></View><FlatList data={visible} keyExtractor={(g) => g.id} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" ListHeaderComponent={<AppInput value={query} onChangeText={setQuery} placeholder="ابحث باسم المجموعة أو المادة أو المدرس..." containerStyle={styles.search} />} ListEmptyComponent={<EmptyState message={query ? "لا توجد نتائج مطابقة." : "لا توجد مجموعات متاحة للرصد."} />} renderItem={({ item }) => { const schedules = GroupScheduleRepository.getSchedulesForGroup(item.id).filter((s) => s.status !== "inactive"); return <TouchableOpacity onPress={() => router.push({ pathname: "/(main)/grades", params: { groupId: item.id } } as any)} style={[styles.card, { backgroundColor: colors.cardBackground, borderColor: colors.border }]}><View style={[styles.icon, { backgroundColor: colors.primaryLight }]}><Ionicons name="reader-outline" size={21} color={colors.primary} /></View><View style={styles.cardCopy}><Text style={[styles.name, { color: colors.textPrimary }]}>{item.name}</Text><Text style={[styles.meta, { color: colors.textSecondary }]}>{[item.subjectName, item.grade, item.teacherName].filter(Boolean).join(" · ")}</Text><Text style={[styles.meta, { color: colors.textSecondary }]}>{schedules.length ? schedules.map((s) => `${DAYS[s.dayOfWeek]} ${s.startTime} - ${s.endTime}`).join(" · ") : "لا يوجد جدول محدد"}</Text></View><Ionicons name="chevron-back" size={19} color={colors.slate400} /></TouchableOpacity>; }} /></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1 }, header: { flexDirection: "row-reverse", alignItems: "center", gap: 10, padding: Spacing.lg, borderBottomWidth: 1, borderBottomColor: Colors.border }, back: { width: 40, height: 40, borderRadius: 12, borderWidth: 1, alignItems: "center", justifyContent: "center" }, copy: { flex: 1, alignItems: "flex-end" }, eyebrow: { fontSize: 11, fontWeight: "800" }, title: { ...Typography.h1, marginTop: 2 }, subtitle: { fontSize: 12, marginTop: 3 }, count: { minWidth: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center" }, countText: { fontWeight: "900" }, content: { padding: Spacing.lg, paddingBottom: 32, flexGrow: 1 }, search: { marginBottom: Spacing.md }, card: { flexDirection: "row-reverse", alignItems: "center", gap: 11, padding: 14, borderWidth: 1, borderRadius: 16, marginBottom: 9 }, icon: { width: 42, height: 42, borderRadius: 13, alignItems: "center", justifyContent: "center" }, cardCopy: { flex: 1, alignItems: "flex-end" }, name: { fontSize: 15, fontWeight: "900", textAlign: "right" }, meta: { fontSize: 11, textAlign: "right", marginTop: 4 } });
