export interface PlatformAdmin { id: string; email: string; name?: string; role: "platform_admin"; }
export interface AuthSession { accessToken: string; admin: PlatformAdmin; }
export interface ApiErrorShape { status: number; message: string; code?: string; }
export interface PlatformOverview { centers: { total: number; active: number; suspended: number }; students: { total: number }; devices: { active: number }; sync: { pending: number; failed: number }; health: { api: string; database: string; sync: string }; }
export interface Center { id: string; name: string; code: string; phone?: string | null; address?: string | null; status: "active" | "suspended" | "inactive"; created_at: string; updated_at?: string; student_count?: number; active_device_count?: number; pending_operations?: number; failed_operations?: number; user_count?: number; }
export interface CenterListResponse { items: Center[]; pagination: { page: number; pageSize: number; total: number; totalPages: number }; }
export interface CenterUser { id: string; center_id: string; full_name: string; email: string; phone?: string | null; role: "admin" | "assistant" | "secretary" | "accountant" | "manager"; status: "active" | "inactive" | "suspended"; created_at: string; updated_at: string; }
export interface CenterService { serviceKey: string; name: string; description: string; enabled: boolean; availability: "available" | "not_configured"; updatedAt: string | null; }
export interface CardRange { id: string; center_id: string; start_code: string; end_code: string; status: "active" | "inactive"; created_at: string; updated_at: string; totalCards: string; }
export interface Device { id: string; center_id: string; user_id?: string; device_name?: string; platform?: string; status: "active" | "revoked" | "pending"; last_seen_at?: string; created_at: string; full_name?: string; pending_operations?: number; failed_operations?: number; }
export interface SyncOperation { server_seq: string; operation_id: string; center_id: string; center_name?: string; device_id?: string; device_name?: string; device_status?: Device["status"]; user_id?: string; user_name?: string; operation_type: string; entity_type: string; entity_id?: string; status: "applied" | "rejected" | "conflict"; created_at: string; synced_at?: string; retry_count: number; last_error?: string | null; }
export interface SyncSummary { pending: number; failed: number; successful: number; recent_activity: number; active_syncing_devices: number; revoked_pending_operations: number; last_successful_sync?: string | null; oldest_pending?: string | null; oldest_failed?: string | null; }
export interface SyncFilters { centerId?: string; deviceId?: string; status?: string; operationType?: string; from?: string; to?: string; sort?: "newest" | "oldest" | "retries"; page?: number; pageSize?: number; }
export interface SyncListResponse { items: SyncOperation[]; pagination: CenterListResponse["pagination"]; }
export interface AuditRecord { id: string; actor_id: string; actor_name?: string; actor_email?: string; center_id?: string; center_name?: string; action: string; entity_type: string; entity_id: string; before?: Record<string, unknown> | null; after?: Record<string, unknown> | null; created_at: string; }
export interface SystemHealth { status: "healthy" | "degraded" | "unavailable"; api: { status: string }; database: { status: string }; sync: { status: string }; checked_at: string; }
