import { FormEvent, useEffect, useRef, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ApiError, platformApi } from "../api/client";
import type { Center } from "../types";

function StatusBadge({ status }: { status: Center["status"] }) { return <span className={`status-badge ${status}`}>{status === "active" ? "نشط" : status === "suspended" ? "موقوف" : "غير نشط"}</span>; }

export function CentersPage() {
  const [items, setItems] = useState<Center[]>([]); const [pagination, setPagination] = useState({ page: 1, pageSize: 20, total: 0, totalPages: 0 }); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [showForm, setShowForm] = useState(false); const requestId = useRef(0);
  async function load(page = 1) { const id = ++requestId.current; setLoading(true); setError(""); try { const result = await platformApi.centers({ page, pageSize: 20, search, status }); if (id === requestId.current) { setItems(result.items); setPagination(result.pagination); } } catch (err) { if (id === requestId.current) setError(err instanceof ApiError ? err.message : "حدث خطأ في الخادم، حاول مرة أخرى."); } finally { if (id === requestId.current) setLoading(false); } }
  useEffect(() => { const timer = window.setTimeout(() => { void load(1); }, 300); return () => window.clearTimeout(timer); }, [search, status]);
  return <section><div className="page-heading"><div><p className="eyebrow">إدارة المنصة</p><h2>المراكز</h2><p className="muted">إدارة ومتابعة مراكز FIXION من مكان واحد.</p></div><button className="primary-button compact" onClick={() => setShowForm(true)}>+ إضافة مركز</button></div><div className="toolbar"><input placeholder="البحث باسم المركز أو الكود" value={search} onChange={event => setSearch(event.target.value)} /><select value={status} onChange={event => setStatus(event.target.value)}><option value="">كل الحالات</option><option value="active">نشط</option><option value="suspended">موقوف</option></select><button className="secondary-button" onClick={() => void load(pagination.page)} disabled={loading}>تحديث</button></div>{error && <div className="alert error page-alert">{error}</div>}{loading ? <div className="panel loading-state">جارٍ تحميل المراكز...</div> : items.length === 0 ? <div className="panel empty-state">لا يوجد مراكز مطابقة للبحث</div> : <div className="panel table-wrap"><table><thead><tr><th>اسم المركز</th><th>الحالة</th><th>الطلاب</th><th>الأجهزة النشطة</th><th>عمليات معلقة</th><th>عمليات فاشلة</th><th>تاريخ الإنشاء</th><th /></tr></thead><tbody>{items.map(center => <tr key={center.id}><td><Link to={`/centers/${center.id}`}>{center.name}</Link><small>{center.code}</small></td><td><StatusBadge status={center.status} /></td><td>{center.student_count ?? 0}</td><td>{center.active_device_count ?? 0}</td><td>{center.pending_operations ?? 0}</td><td>{center.failed_operations ?? 0}</td><td>{new Date(center.created_at).toLocaleDateString("ar-EG")}</td><td><Link className="text-link" to={`/centers/${center.id}`}>التفاصيل</Link></td></tr>)}</tbody></table></div>}<div className="pagination"><span className="muted">{pagination.total} مركز</span><button className="secondary-button" disabled={pagination.page <= 1 || loading} onClick={() => void load(pagination.page - 1)}>السابق</button><span>صفحة {pagination.page} من {Math.max(1, pagination.totalPages)}</span><button className="secondary-button" disabled={pagination.page >= pagination.totalPages || loading} onClick={() => void load(pagination.page + 1)}>التالي</button></div>{showForm && <CenterForm onClose={() => setShowForm(false)} onSaved={() => { setShowForm(false); void load(1); }} />}</section>;
}

function CenterForm({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) { const [name, setName] = useState(""); const [code, setCode] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); if (name.trim().length < 2 || !code.trim()) { setError("اسم المركز والكود مطلوبان."); return; } setSaving(true); try { await platformApi.createCenter({ name: name.trim(), code: code.trim() }); onSaved(); } catch (err) { setError(err instanceof ApiError ? err.message : "تعذر إنشاء المركز."); } finally { setSaving(false); } } return <div className="modal-backdrop"><form className="modal-card" onSubmit={submit}><h3>إضافة مركز</h3><label>اسم المركز<input value={name} onChange={event => setName(event.target.value)} maxLength={255} required /></label><label>كود المركز<input value={code} onChange={event => setCode(event.target.value)} maxLength={64} required /></label>{error && <div className="alert error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>إلغاء</button><button className="primary-button" disabled={saving}>{saving ? "جارٍ الحفظ..." : "حفظ"}</button></div></form></div>; }

export function CenterDetailsPage() { const navigate = useNavigate(); const id = window.location.pathname.split("/").pop() ?? ""; const [center, setCenter] = useState<Center | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); useEffect(() => { void platformApi.center(id).then(result => setCenter(result.center)).catch(err => setError(err instanceof ApiError ? err.message : "تعذر تحميل المركز.")).finally(() => setLoading(false)); }, [id]); async function toggleStatus() { if (!center || !window.confirm(center.status === "active" ? "هل أنت متأكد من إيقاف هذا المركز؟" : "هل تريد إعادة تفعيل هذا المركز؟")) return; setSaving(true); try { const result = await platformApi.updateCenter(center.id, { status: center.status === "active" ? "suspended" : "active" }); setCenter(result.center); } catch (err) { setError(err instanceof ApiError ? err.message : "تعذر تحديث حالة المركز."); } finally { setSaving(false); } } if (loading) return <div className="panel loading-state">جارٍ تحميل بيانات المركز...</div>; if (error || !center) return <div className="panel alert error">{error || "المركز غير موجود"}</div>; return <section><button className="back-link" onClick={() => navigate("/centers")}>← العودة للمراكز</button><div className="page-heading"><div><p className="eyebrow">تفاصيل المركز</p><h2>{center.name}</h2><p className="muted">كود المركز: {center.code}</p></div><div><StatusBadge status={center.status} /><button className="secondary-button action-button" onClick={() => void toggleStatus()} disabled={saving}>{saving ? "جارٍ الحفظ..." : center.status === "active" ? "إيقاف المركز" : "إعادة التفعيل"}</button></div></div><div className="kpi-grid"><article className="kpi-card"><span className="muted">الطلاب</span><strong>{center.student_count ?? 0}</strong></article><article className="kpi-card"><span className="muted">الأجهزة النشطة</span><strong>{center.active_device_count ?? 0}</strong></article><article className="kpi-card"><span className="muted">عمليات معلقة</span><strong>{center.pending_operations ?? 0}</strong></article><article className="kpi-card"><span className="muted">عمليات فاشلة</span><strong>{center.failed_operations ?? 0}</strong></article></div><div className="panel details-grid"><div><span className="muted">الحالة</span><strong><StatusBadge status={center.status} /></strong></div><div><span className="muted">تاريخ الإنشاء</span><strong>{new Date(center.created_at).toLocaleDateString("ar-EG")}</strong></div><div><span className="muted">المستخدمون النشطون</span><strong>{center.user_count ?? 0}</strong></div></div></section>; }
