import { useEffect, useState } from "react";
import { ApiError, platformApi } from "../api/client";
import type { Center, CenterService } from "../types";

export function ServicesPage(){
  const [centers,setCenters]=useState<Center[]>([]);const [centerId,setCenterId]=useState("");const [services,setServices]=useState<CenterService[]>([]);const [loading,setLoading]=useState(false);const [pendingKey,setPendingKey]=useState("");const [error,setError]=useState("");
  useEffect(()=>{void platformApi.centers({pageSize:100}).then(r=>{setCenters(r.items);if(r.items[0])setCenterId(r.items[0].id);}).catch(e=>setError(e instanceof ApiError?e.message:"تعذر تحميل المراكز."));},[]);
  async function load(){if(!centerId)return;setLoading(true);setError("");try{setServices((await platformApi.services(centerId)).services);}catch(e){setError(e instanceof ApiError?e.message:"تعذر تحميل الخدمات.");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[centerId]);
  async function toggle(service:CenterService){if(!centerId||pendingKey||service.availability==="not_configured")return;const enabled=!service.enabled;setPendingKey(service.serviceKey);setError("");try{const result=await platformApi.updateService(centerId,service.serviceKey,enabled);setServices(current=>current.map(item=>item.serviceKey===service.serviceKey?{...item,enabled:result.service.enabled,updatedAt:result.service.updatedAt}:item));}catch(e){setError(e instanceof ApiError?e.message:"تعذر تحديث الخدمة.");}finally{setPendingKey("");}}
  return <section><div className="page-heading"><div><p className="eyebrow">إدارة المنصة</p><h2>الخدمات</h2><p className="muted">تحكم في الخدمات المتاحة لكل مركز. التعطيل يتم فرضه من الخادم.</p></div><button type="button" className="secondary-button" onClick={()=>void load()} disabled={loading||!!pendingKey}>تحديث</button></div><div className="toolbar"><select value={centerId} onChange={e=>setCenterId(e.target.value)}><option value="">اختر المركز</option>{centers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>{error&&<div className="alert error page-alert">{error}</div>}{loading?<div className="panel loading-state">جارٍ تحميل الخدمات...</div>:<div className="panel table-wrap"><table><thead><tr><th>الخدمة</th><th>الوصف</th><th>الحالة</th><th>الإتاحة</th><th>الإجراء</th></tr></thead><tbody>{services.map(service=><tr key={service.serviceKey}><td>{service.name}</td><td>{service.description}</td><td><span className={`status-badge ${service.enabled?"active":"suspended"}`}>{service.enabled?"مفعلة":"متوقفة"}</span></td><td>{service.availability==="not_configured"?"غير مهيأة":"متاحة"}</td><td><button type="button" className="text-button" disabled={service.availability==="not_configured"||!!pendingKey} onClick={()=>void toggle(service)}>{pendingKey===service.serviceKey?"جارٍ الحفظ...":service.enabled?"إيقاف":"تفعيل"}</button></td></tr>)}</tbody></table>{!services.length&&!loading&&<div className="empty-state">لا توجد خدمات لهذا المركز</div>}</div>}</section>;
}
