const express = require("express");
const db = require("../db");
const { platformAuthMiddleware } = require("../middleware/platformAuth");
const router = express.Router();
router.use(platformAuthMiddleware);
const sorts = { newest: "a.timestamp DESC", oldest: "a.timestamp ASC" };
function filters(query) { const values = []; const where = []; const add = (value, clause) => { values.push(value); where.push(clause.replace("$N", `$${values.length}`)); }; if (query.centerId) add(String(query.centerId), "a.center_id=$N"); if (query.actorId) add(String(query.actorId), "a.actor_id=$N"); if (query.action) add(String(query.action), "a.action=$N"); if (query.entityType) add(String(query.entityType), "a.entity_type=$N"); if (query.from) add(String(query.from), "a.timestamp >= $N"); if (query.to) add(String(query.to), "a.timestamp <= $N"); return { values, where: where.length ? where.join(" AND ") : "TRUE" }; }
async function list(req, res, next) { try { const { values, where } = filters(req.query); const page = Math.max(1, Number.parseInt(req.query.page, 10) || 1); const pageSize = Math.min(100, Math.max(1, Number.parseInt(req.query.pageSize, 10) || 20)); const count = await db.query(`SELECT COUNT(*)::int AS total FROM audit_logs a WHERE ${where} AND a.actor_type='platform_admin'`, values); const params = values.concat([pageSize, (page - 1) * pageSize]); const rows = await db.query(`SELECT a.id,a.actor_type,a.actor_id,a.center_id,c.name AS center_name,a.action,a.entity_type,a.entity_id,a.before_state AS before,a.after_state AS after,a.metadata,a.timestamp AS created_at,p.full_name AS actor_name,p.email AS actor_email FROM audit_logs a LEFT JOIN centers c ON c.id=a.center_id LEFT JOIN platform_admins p ON p.id=a.actor_id WHERE ${where} AND a.actor_type='platform_admin' ORDER BY ${sorts[req.query.sort] || sorts.newest} LIMIT $${params.length - 1} OFFSET $${params.length}`, params); res.json({ items: rows.rows, pagination: { page, pageSize, total: count.rows[0].total, totalPages: Math.ceil(count.rows[0].total / pageSize) } }); } catch (error) { next(error); } }
router.get("/", list);
router.get("/:auditId", async (req, res, next) => { try { const { rows } = await db.query(`SELECT a.id,a.actor_type,a.actor_id,a.center_id,c.name AS center_name,a.action,a.entity_type,a.entity_id,a.before_state AS before,a.after_state AS after,a.metadata,a.timestamp AS created_at,p.full_name AS actor_name,p.email AS actor_email FROM audit_logs a LEFT JOIN centers c ON c.id=a.center_id LEFT JOIN platform_admins p ON p.id=a.actor_id WHERE a.id=$1 AND a.actor_type='platform_admin'`, [req.params.auditId]); if (!rows[0]) return res.status(404).json({ error: { code: "NOT_FOUND", userMessage: "سجل النشاط غير موجود." } }); res.json({ audit: rows[0] }); } catch (error) { next(error); } });
module.exports = { router, list };
