import type { ApiErrorShape, SyncFilters, SyncListResponse, SyncSummary } from "../types";
const API_BASE_URL=(import.meta.env.VITE_API_BASE_URL as string|undefined)?.replace(/\/$/,"")??"http://localhost:3000/v1";
export class ApiError extends Error implements ApiErrorShape { constructor(public status:number,message:string,public code?:string){super(message);this.name="ApiError";} }
function userMessage(status:number){if(status===401)return "انتهت جلسة الدخول.";if(status===403)return "ليس لديك صلاحية لتنفيذ هذا الإجراء.";if(status===404)return "الخدمة المطلوبة غير موجودة.";if(status>=500)return "الخادم غير متاح مؤقتًا.";return "تعذر تنفيذ الطلب.";}
export async function apiRequest<T>(path:string,options:RequestInit={}):Promise<T>{const token=localStorage.getItem("fixion.platform.accessToken");const response=await fetch(`${API_BASE_URL}${path}`,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{ }),...options.headers}});const body:unknown=await response.json().catch(()=>null);if(!response.ok){const errorBody=typeof body==="object"&&body!==null&&"error" in body&&typeof body.error==="object"&&body.error!==null?body.error:null;const message=errorBody&&"userMessage" in errorBody&&typeof errorBody.userMessage==="string"?errorBody.userMessage:userMessage(response.status);throw new ApiError(response.status,message);}return body as T;}
const query=(params:object)=>new URLSearchParams(Object.entries(params).filter(([,v])=>v!==undefined&&v!=="").map(([k,v])=>[k,String(v)]));
export const platformApi={login:async(email:string,password:string)=>{const r=await apiRequest<any>("/platform/auth/login",{method:"POST",body:JSON.stringify({email,password})});return{session:{accessToken:r.token,admin:{id:r.user.id,name:r.user.fullName,email:r.user.email,role:r.user.role}}};},overview:()=>apiRequest<any>("/platform/overview"),centers:(params:Record<string,unknown>={})=>apiRequest<any>(`/platform/centers?${query(params)}`),center:(id:string)=>apiRequest<any>(`/platform/centers/${encodeURIComponent(id)}`),createCenter:(payload:Record<string,unknown>)=>apiRequest<any>("/platform/centers",{method:"POST",body:JSON.stringify(payload)}),updateCenter:(id:string,payload:Record<string,unknown>)=>apiRequest<any>(`/platform/centers/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(payload)}),users:(id:string,params:Record<string,unknown>={})=>apiRequest<any>(`/platform/centers/${encodeURIComponent(id)}/users?${query(params)}`),createUser:(id:string,payload:Record<string,string>)=>apiRequest<any>(`/platform/centers/${encodeURIComponent(id)}/users`,{method:"POST",body:JSON.stringify(payload)}),updateUser:(id:string,uid:string,payload:Record<string,string>)=>apiRequest<any>(`/platform/centers/${encodeURIComponent(id)}/users/${encodeURIComponent(uid)}`,{method:"PATCH",body:JSON.stringify(payload)}),setUserStatus:(id:string,uid:string,status:"active"|"inactive")=>apiRequest<any>(`/platform/centers/${encodeURIComponent(id)}/users/${encodeURIComponent(uid)}/${status==="active"?"activate":"deactivate"}`,{method:"POST"}),services:(id:string)=>apiRequest<any>(`/platform/centers/${encodeURIComponent(id)}/services`),updateService:(id:string,key:string,enabled:boolean)=>apiRequest<any>(`/platform/centers/${encodeURIComponent(id)}/services/${encodeURIComponent(key)}`,{method:"PATCH",body:JSON.stringify({enabled})}),ranges:(id:string)=>apiRequest<any>(`/platform/centers/${encodeURIComponent(id)}/card-ranges`),createRange:(id:string,startCode:string,endCode:string)=>apiRequest<any>(`/platform/centers/${encodeURIComponent(id)}/card-ranges`,{method:"POST",body:JSON.stringify({startCode,endCode})}),devices:(id:string,params:Record<string,unknown>={})=>apiRequest<any>(`/platform/centers/${encodeURIComponent(id)}/devices?${query(params)}`),setDeviceStatus:(id:string,did:string,status:"active"|"revoked")=>apiRequest<any>(`/platform/centers/${encodeURIComponent(id)}/devices/${encodeURIComponent(did)}/${status==="active"?"activate":"deactivate"}`,{method:"POST"}),sync:(id:string,params:SyncFilters={})=>apiRequest<SyncListResponse>(`/platform/centers/${encodeURIComponent(id)}/sync?${query(params)}`),syncList:(params:SyncFilters={})=>apiRequest<SyncListResponse>(`/platform/sync?${query(params)}`),syncSummary:(params:Pick<SyncFilters,"centerId"|"deviceId">={})=>apiRequest<{summary:SyncSummary}>(`/platform/sync/summary?${query(params)}`)};
export const auditApi={list:(params:Record<string,unknown>={})=>apiRequest<{items:import("../types").AuditRecord[];pagination:import("../types").CenterListResponse["pagination"]}>(`/platform/audit-logs?${query(params)}`),detail:(id:string)=>apiRequest<{audit:import("../types").AuditRecord}>(`/platform/audit-logs/${encodeURIComponent(id)}`)};
export const healthApi={get:()=>apiRequest<import("../types").SystemHealth>("/platform/health")};
